// ═══════════════════════════════════════════════════════════
// CONSTANTES — Module Bella'Food — Partie I
// Catalogue, recettes, stocks, matériel, consommables
// ═══════════════════════════════════════════════════════════
import type {
  Produit, Recette, StockItem, Materiel, Consommable,
  CategorieRecette,
} from "./foodTypes";

// ── Palette Bella'Food ─────────────────────────────────────
export const FOOD_COLORS = {
  or:      "#c9a96e",
  vert:    "#15803d",
  vertL:   "#22c55e",
  vertD:   "#052e16",
  cream:   "#fef9f0",
  creamD:  "#d4b896",
  surface: "rgba(21,128,61,0.08)",
  line:    "rgba(21,128,61,0.2)",
  card:    "rgba(255,255,255,0.04)",
  border:  "rgba(255,255,255,0.1)",
  night:   "#0a0f0a",
  muted:   "rgba(255,255,255,0.45)",
};

// ── 38 catégories du catalogue ─────────────────────────────
export const FOOD_CATEGORIES: { id: CategorieRecette; nom: string; ico: string; groupe: string }[] = [
  // Cuisine salée
  {id:"entree",         nom:"Entrées",           ico:"🥗", groupe:"cuisine"},
  {id:"soupe",          nom:"Soupes",             ico:"🥣", groupe:"cuisine"},
  {id:"salade",         nom:"Salades",            ico:"🥬", groupe:"cuisine"},
  {id:"viande",         nom:"Viandes",            ico:"🥩", groupe:"cuisine"},
  {id:"poisson",        nom:"Poissons",           ico:"🐟", groupe:"cuisine"},
  {id:"fruits_de_mer",  nom:"Fruits de mer",      ico:"🦐", groupe:"cuisine"},
  {id:"poulet",         nom:"Poulet",             ico:"🍗", groupe:"cuisine"},
  {id:"boeuf",          nom:"Bœuf",               ico:"🐄", groupe:"cuisine"},
  {id:"agneau",         nom:"Agneau",             ico:"🐑", groupe:"cuisine"},
  {id:"accompagnement", nom:"Accompagnements",    ico:"🥗", groupe:"cuisine"},
  {id:"riz",            nom:"Riz",                ico:"🍚", groupe:"cuisine"},
  {id:"pates",          nom:"Pâtes",              ico:"🍝", groupe:"cuisine"},
  {id:"burger",         nom:"Burgers",            ico:"🍔", groupe:"cuisine"},
  {id:"sandwich",       nom:"Sandwichs",          ico:"🥪", groupe:"cuisine"},
  {id:"street_food",    nom:"Street Food",        ico:"🌮", groupe:"cuisine"},
  {id:"sauce",          nom:"Sauces",             ico:"🫙", groupe:"cuisine"},
  {id:"repas_creole",   nom:"Repas créoles",      ico:"🌴", groupe:"cuisine"},
  {id:"repas_guyanais", nom:"Repas guyanais",     ico:"🌿", groupe:"cuisine"},
  // Pâtisserie
  {id:"patisserie",     nom:"Pâtisserie",         ico:"🎂", groupe:"patisserie"},
  {id:"cake",           nom:"Cakes",              ico:"🍰", groupe:"patisserie"},
  {id:"cupcake",        nom:"Cupcakes",           ico:"🧁", groupe:"patisserie"},
  {id:"entremet",       nom:"Entremets",          ico:"🍮", groupe:"patisserie"},
  {id:"macaron",        nom:"Macarons",           ico:"🫐", groupe:"patisserie"},
  {id:"viennoiserie",   nom:"Viennoiseries",      ico:"🥐", groupe:"patisserie"},
  {id:"pain",           nom:"Pain",               ico:"🍞", groupe:"patisserie"},
  {id:"dessert",        nom:"Desserts",           ico:"🍨", groupe:"patisserie"},
  {id:"glace",          nom:"Glacerie",           ico:"🍦", groupe:"patisserie"},
  // Boissons
  {id:"boisson",        nom:"Boissons",           ico:"🥤", groupe:"boissons"},
  {id:"jus",            nom:"Jus",                ico:"🧃", groupe:"boissons"},
  {id:"smoothie",       nom:"Smoothies",          ico:"🥤", groupe:"boissons"},
  {id:"the_glace",      nom:"Thés glacés",        ico:"🫖", groupe:"boissons"},
  {id:"cocktail",       nom:"Cocktails",          ico:"🍹", groupe:"boissons"},
  {id:"mocktail",       nom:"Mocktails",          ico:"🍋", groupe:"boissons"},
  // Événements
  {id:"buffet",         nom:"Buffets",            ico:"🍱", groupe:"evenements"},
  {id:"traiteur",       nom:"Traiteur",           ico:"🥘", groupe:"evenements"},
  {id:"brunch",         nom:"Brunch",             ico:"☕",  groupe:"evenements"},
  {id:"mariage",        nom:"Mariage",            ico:"💒", groupe:"evenements"},
  {id:"baby_shower",    nom:"Baby Shower",        ico:"🍼", groupe:"evenements"},
  {id:"anniversaire",   nom:"Anniversaire",       ico:"🎉", groupe:"evenements"},
];

// ── Catalogue produits ─────────────────────────────────────
export const FOOD_CATALOGUE: Produit[] = [
  // Cakes
  {id:"f_layer_cake",    nom:"Layer Cake personnalisé",       categorie:"cake",         sousCat:"layer",    prix:45,  unite:"prestation",   disponible:true, visibleEvents:true,  description:"À étages, décoré thème"},
  {id:"f_bento_cake",    nom:"Bento Cake",                    categorie:"cake",         sousCat:"bento",    prix:25,  unite:"pièce",        disponible:true, visibleEvents:true},
  {id:"f_heart_cake",    nom:"Heart Cake",                    categorie:"cake",         sousCat:"heart",    prix:35,  unite:"pièce",        disponible:true, visibleEvents:true},
  {id:"f_number_cake",   nom:"Number Cake",                   categorie:"cake",         sousCat:"number",   prix:null,unite:"pièce",        disponible:true, visibleEvents:true,  description:"Sur devis selon chiffre"},
  {id:"f_gateau_ps",     nom:"Gâteau pâte à sucre",           categorie:"cake",         sousCat:"fondant",  prix:45,  unite:"prestation",   disponible:true, visibleEvents:true},
  {id:"f_wedding_cake",  nom:"Wedding Cake",                  categorie:"mariage",      sousCat:"wedding",  prix:null,unite:"prestation",   disponible:true, visibleEvents:true,  description:"Sur devis — plusieurs étages"},
  // Cupcakes & petits gâteaux
  {id:"f_cupcakes",      nom:"Cupcakes décorés",              categorie:"cupcake",      sousCat:"deco",     prix:28,  unite:"douzaine",     disponible:true, visibleEvents:true},
  {id:"f_cookies",       nom:"Cookies",                       categorie:"patisserie",   sousCat:"biscuit",  prix:12,  unite:"6 pièces",     disponible:true},
  {id:"f_brownies",      nom:"Brownies",                      categorie:"patisserie",   sousCat:"biscuit",  prix:15,  unite:"plaque",       disponible:true},
  {id:"f_donuts",        nom:"Donuts glacés",                 categorie:"patisserie",   sousCat:"viennoiserie",prix:18,unite:"6 pièces",    disponible:true},
  {id:"f_cake_pops",     nom:"Cake Pops",                     categorie:"patisserie",   sousCat:"sucette",  prix:20,  unite:"10 pièces",    disponible:true, visibleEvents:true},
  {id:"f_macarons",      nom:"Macarons",                      categorie:"macaron",      sousCat:"classique",prix:null,unite:"douzaine",     disponible:true, visibleEvents:true},
  {id:"f_entremets",     nom:"Entremets",                     categorie:"entremet",     sousCat:"classique",prix:null,unite:"pièce",        disponible:true, description:"Sur devis"},
  {id:"f_mignardises",   nom:"Plateau de mignardises",        categorie:"patisserie",   sousCat:"plateau",  prix:null,unite:"plateau",      disponible:true, visibleEvents:true},
  {id:"f_box_patisserie",nom:"Box pâtisserie",                categorie:"patisserie",   sousCat:"box",      prix:null,unite:"box",          disponible:true},
  // Jus frais
  {id:"f_jus_canne",     nom:"Jus de canne",                  categorie:"jus",          sousCat:"tropicaux",prix:3,   unite:"verre",        disponible:true, visibleEvents:true},
  {id:"f_jus_mangue",    nom:"Jus de mangue",                 categorie:"jus",          sousCat:"tropicaux",prix:3,   unite:"verre",        disponible:true, visibleEvents:true},
  {id:"f_jus_groseille", nom:"Jus de groseille",              categorie:"jus",          sousCat:"tropicaux",prix:3,   unite:"verre",        disponible:true, visibleEvents:true},
  {id:"f_jus_coco",      nom:"Eau de coco",                   categorie:"jus",          sousCat:"tropicaux",prix:4,   unite:"verre",        disponible:true, visibleEvents:true},
  {id:"f_jus_ananas",    nom:"Jus d'ananas",                  categorie:"jus",          sousCat:"tropicaux",prix:3,   unite:"verre",        disponible:true, visibleEvents:true},
  {id:"f_jus_cerise",    nom:"Jus de cerises",                categorie:"jus",          sousCat:"locaux",   prix:3.5, unite:"verre",        disponible:true},
  {id:"f_jus_cupuacu",   nom:"Jus de cupuaçu",                categorie:"jus",          sousCat:"amazonie", prix:4,   unite:"verre",        disponible:true},
  {id:"f_jus_pommarosa", nom:"Jus de pomme rosa",             categorie:"jus",          sousCat:"locaux",   prix:3.5, unite:"verre",        disponible:true},
  {id:"f_jus_pommamour", nom:"Jus de pomme d'amour",          categorie:"jus",          sousCat:"locaux",   prix:3.5, unite:"verre",        disponible:true},
  {id:"f_jus_citron",    nom:"Jus de citron",                 categorie:"jus",          sousCat:"classiques",prix:2.5,unite:"verre",        disponible:true, visibleEvents:true},
  // Thés glacés
  {id:"f_the_citronelle",nom:"Thé glacé citronnelle",         categorie:"the_glace",    sousCat:"herbes",   prix:3,   unite:"verre",        disponible:true, visibleEvents:true},
  {id:"f_the_cannelle",  nom:"Thé glacé cannelle",            categorie:"the_glace",    sousCat:"epices",   prix:3,   unite:"verre",        disponible:true},
  {id:"f_the_citron",    nom:"Thé glacé citron",              categorie:"the_glace",    sousCat:"classiques",prix:3,  unite:"verre",        disponible:true},
  // Glacerie
  {id:"f_glace_coco",    nom:"Glace coco",                    categorie:"glace",        sousCat:"artisanale",prix:3,  unite:"boule",        disponible:true, visibleEvents:true},
  {id:"f_sorbet_cacah",  nom:"Sorbet cacahuète",              categorie:"glace",        sousCat:"artisanale",prix:3,  unite:"boule",        disponible:true},
  {id:"f_glace_awara",   nom:"Glace awara",                   categorie:"glace",        sousCat:"local",    prix:3.5, unite:"boule",        disponible:true},
  {id:"f_glace_acai",    nom:"Glace açaï",                    categorie:"glace",        sousCat:"amazonie", prix:3.5, unite:"boule",        disponible:true},
  {id:"f_glace_rhum",    nom:"Glace rhum-raisin",             categorie:"glace",        sousCat:"artisanale",prix:3,  unite:"boule",        disponible:true},
  {id:"f_glace_mangue",  nom:"Glace mangue",                  categorie:"glace",        sousCat:"tropicaux",prix:3,   unite:"boule",        disponible:true, visibleEvents:true},
  // Cuisine salée
  {id:"f_colombo",       nom:"Colombo de poulet",             categorie:"repas_guyanais",sousCat:"plats",   prix:null,unite:"portion",      disponible:true, visibleEvents:true},
  {id:"f_dombres",       nom:"Dombrés aux crevettes",         categorie:"repas_guyanais",sousCat:"plats",   prix:null,unite:"portion",      disponible:true, visibleEvents:true},
  {id:"f_crevettes_curry",nom:"Crevettes curry coco",         categorie:"repas_guyanais",sousCat:"plats",   prix:null,unite:"portion",      disponible:true, visibleEvents:true},
  {id:"f_riz_djon",      nom:"Riz djon djon",                 categorie:"riz",           sousCat:"parfume", prix:null,unite:"portion",      disponible:true},
  {id:"f_riz_canton",    nom:"Riz cantonais",                 categorie:"riz",           sousCat:"asiatique",prix:null,unite:"portion",     disponible:true},
  {id:"f_lentilles",     nom:"Lentilles mijotées aux légumes",categorie:"repas_guyanais",sousCat:"veggie",  prix:null,unite:"portion",      disponible:true},
  {id:"f_saumon",        nom:"Saumon au four, légumes rôtis", categorie:"poisson",       sousCat:"four",    prix:null,unite:"portion",      disponible:true},
  {id:"f_poulet_grill",  nom:"Poulet grillé, riz complet",   categorie:"poulet",        sousCat:"grill",   prix:null,unite:"portion",      disponible:true},
  {id:"f_feuillete",     nom:"Feuilletés au poulet",          categorie:"entree",        sousCat:"chauds",  prix:null,unite:"pièce",        disponible:true, visibleEvents:true},
  // Sauces
  {id:"f_sauce_burger",  nom:"Sauce burger maison",           categorie:"sauce",         sousCat:"froide",  prix:null,unite:"portion",      disponible:true},
  {id:"f_sauce_roquefort",nom:"Sauce roquefort",              categorie:"sauce",         sousCat:"froide",  prix:null,unite:"portion",      disponible:true},
  // Options
  {id:"f_option_saveur", nom:"Option saveur spéciale",        categorie:"patisserie",    sousCat:"option",  prix:5,   unite:"option",       disponible:true, visibleEvents:true, description:"Caramel, pralinée, chocolat..."},
  // Buffets & traiteur
  {id:"f_buffet_sucre",  nom:"Buffet sucré",                  categorie:"buffet",        sousCat:"sucre",   prix:8,   unite:"par personne", disponible:true, visibleEvents:true},
  {id:"f_buffet_cocktail",nom:"Buffet cocktail",              categorie:"buffet",        sousCat:"aperitif",prix:15,  unite:"par personne", disponible:true, visibleEvents:true},
  {id:"f_repas_servi",   nom:"Repas servi (plat + dessert)",  categorie:"traiteur",      sousCat:"complet", prix:22,  unite:"par personne", disponible:true, visibleEvents:true},
];

// ── Stocks initiaux ────────────────────────────────────────
export const FOOD_STOCK_INIT: StockItem[] = [
  {id:"s_farine",      nom:"Farine T55",             categorie:"sec",        unite:"kg",     qteRestante:5,   seuilAlerte:2,   prixAchat:1.2},
  {id:"s_farine_t65",  nom:"Farine T65",             categorie:"sec",        unite:"kg",     qteRestante:2,   seuilAlerte:1,   prixAchat:1.4},
  {id:"s_sucre_blanc", nom:"Sucre blanc",            categorie:"sec",        unite:"kg",     qteRestante:3,   seuilAlerte:1,   prixAchat:0.9},
  {id:"s_sucre_gl",    nom:"Sucre glace",            categorie:"sec",        unite:"kg",     qteRestante:1,   seuilAlerte:0.5, prixAchat:1.5},
  {id:"s_sucre_cas",   nom:"Cassonade",              categorie:"sec",        unite:"kg",     qteRestante:0.5, seuilAlerte:0.2, prixAchat:1.8},
  {id:"s_beurre",      nom:"Beurre doux",            categorie:"frais",      unite:"kg",     qteRestante:1,   seuilAlerte:0.5, prixAchat:8},
  {id:"s_beurre_sale", nom:"Beurre salé",            categorie:"frais",      unite:"kg",     qteRestante:0.5, seuilAlerte:0.2, prixAchat:8.5},
  {id:"s_oeufs",       nom:"Œufs (lot 12)",          categorie:"frais",      unite:"boite",  qteRestante:2,   seuilAlerte:1,   prixAchat:3.5},
  {id:"s_lait",        nom:"Lait entier",            categorie:"frais",      unite:"L",      qteRestante:2,   seuilAlerte:1,   prixAchat:1.2},
  {id:"s_creme_liq",   nom:"Crème liquide 30%",      categorie:"frais",      unite:"L",      qteRestante:1,   seuilAlerte:0.5, prixAchat:2.5},
  {id:"s_creme_ep",    nom:"Crème épaisse",          categorie:"frais",      unite:"pot",    qteRestante:2,   seuilAlerte:1,   prixAchat:1.8},
  {id:"s_choc_noir",   nom:"Chocolat noir 70%",      categorie:"sec",        unite:"kg",     qteRestante:0.5, seuilAlerte:0.2, prixAchat:12},
  {id:"s_choc_blanc",  nom:"Chocolat blanc",         categorie:"sec",        unite:"kg",     qteRestante:0.5, seuilAlerte:0.2, prixAchat:10},
  {id:"s_choc_lait",   nom:"Chocolat au lait",       categorie:"sec",        unite:"kg",     qteRestante:0.3, seuilAlerte:0.1, prixAchat:9},
  {id:"s_levure_ch",   nom:"Levure chimique",        categorie:"sec",        unite:"sachet", qteRestante:5,   seuilAlerte:2,   prixAchat:0.5},
  {id:"s_levure_br",   nom:"Levure boulangère",      categorie:"sec",        unite:"sachet", qteRestante:4,   seuilAlerte:2,   prixAchat:0.6},
  {id:"s_vanille",     nom:"Extrait de vanille",     categorie:"aromes",     unite:"ml",     qteRestante:100, seuilAlerte:20,  prixAchat:0.05},
  {id:"s_pate_amande", nom:"Pâte d'amande",          categorie:"garnitures", unite:"kg",     qteRestante:0.5, seuilAlerte:0.2, prixAchat:18},
  {id:"s_fondant_dec", nom:"Pâte à sucre blanche",   categorie:"garnitures", unite:"kg",     qteRestante:1,   seuilAlerte:0.3, prixAchat:12},
  {id:"s_caramel",     nom:"Caramel beurre salé",    categorie:"garnitures", unite:"kg",     qteRestante:0.3, seuilAlerte:0.1, prixAchat:15},
  {id:"s_colorants",   nom:"Colorants alimentaires", categorie:"colorants",  unite:"boite",  qteRestante:1,   seuilAlerte:0,   prixAchat:8},
  {id:"s_colombo_pdr", nom:"Poudre à colombo",       categorie:"epices",     unite:"g",      qteRestante:200, seuilAlerte:50,  prixAchat:0.04},
  {id:"s_curcuma",     nom:"Curcuma",                categorie:"epices",     unite:"g",      qteRestante:100, seuilAlerte:30,  prixAchat:0.03},
  {id:"s_lait_coco",   nom:"Lait de coco",           categorie:"conserves",  unite:"L",      qteRestante:3,   seuilAlerte:1,   prixAchat:1.8},
];

// ── Matériel ───────────────────────────────────────────────
export const FOOD_MATERIEL_INIT: Materiel[] = [
  {id:"m_four",         nom:"Four",                        categorie:"cuisson",    qteDispo:1, etat:"bon",      prixAchat:400,  priorite:"urgent"},
  {id:"m_kitchenaid",   nom:"KitchenAid",                  categorie:"patisserie", qteDispo:0, etat:"manquant", prixAchat:600,  priorite:"urgent"},
  {id:"m_robot_pat",    nom:"Robot pâtissier",             categorie:"patisserie", qteDispo:0, etat:"manquant", prixAchat:350,  priorite:"urgent"},
  {id:"m_blender",      nom:"Blender",                     categorie:"boissons",   qteDispo:1, etat:"bon",      prixAchat:60,   priorite:"utile"},
  {id:"m_ninja_slushi", nom:"Ninja Slushi",                categorie:"glace",      qteDispo:0, etat:"manquant", prixAchat:150,  priorite:"utile"},
  {id:"m_mixeur_plong", nom:"Mixeur plongeant",            categorie:"cuisson",    qteDispo:1, etat:"bon",      prixAchat:45,   priorite:"utile"},
  {id:"m_batteur",      nom:"Batteur électrique",          categorie:"patisserie", qteDispo:1, etat:"bon",      prixAchat:35,   priorite:"utile"},
  {id:"m_balance",      nom:"Balance de précision",        categorie:"mesure",     qteDispo:1, etat:"bon",      prixAchat:30,   priorite:"urgent"},
  {id:"m_thermometre",  nom:"Thermomètre de cuisson",      categorie:"mesure",     qteDispo:1, etat:"bon",      prixAchat:20,   priorite:"urgent"},
  {id:"m_maryse_gr",    nom:"Maryses (jeu 3)",             categorie:"patisserie", qteDispo:3, etat:"bon",      prixAchat:3,    priorite:"utile"},
  {id:"m_spatule_coud", nom:"Spatule coudée",              categorie:"patisserie", qteDispo:2, etat:"bon",      prixAchat:6,    priorite:"utile"},
  {id:"m_douilles",     nom:"Jeu de douilles",             categorie:"decoration", qteDispo:1, etat:"bon",      prixAchat:25,   priorite:"utile"},
  {id:"m_moule_layer",  nom:"Moules layer cake (Ø15/18/20)",categorie:"patisserie",qteDispo:1, etat:"bon",      prixAchat:35,   priorite:"utile"},
  {id:"m_moule_bento",  nom:"Moules bento cake",           categorie:"patisserie", qteDispo:4, etat:"bon",      prixAchat:8,    priorite:"utile"},
  {id:"m_moule_cup",    nom:"Moules cupcakes (12 alvéoles)",categorie:"patisserie",qteDispo:2, etat:"bon",      prixAchat:12,   priorite:"utile"},
  {id:"m_cercles",      nom:"Cercles à entremets",         categorie:"patisserie", qteDispo:2, etat:"bon",      prixAchat:12,   priorite:"utile"},
  {id:"m_plaques",      nom:"Plaques de cuisson",          categorie:"cuisson",    qteDispo:3, etat:"bon",      prixAchat:15,   priorite:"utile"},
  {id:"m_poches",       nom:"Poches à douille (50 pcs)",   categorie:"patisserie", qteDispo:1, etat:"bon",      prixAchat:8,    priorite:"urgent"},
  {id:"m_grilles",      nom:"Grilles de refroidissement",  categorie:"cuisson",    qteDispo:2, etat:"bon",      prixAchat:10,   priorite:"utile"},
  {id:"m_glacieres",    nom:"Glacières",                   categorie:"transport",  qteDispo:2, etat:"bon",      prixAchat:25,   priorite:"utile"},
  {id:"m_boites_tr",    nom:"Boîtes de transport gâteaux", categorie:"transport",  qteDispo:5, etat:"bon",      prixAchat:3,    priorite:"utile"},
];

// ── Consommables ───────────────────────────────────────────
export const FOOD_CONSOMMABLES_INIT: Consommable[] = [
  {id:"c_cake_boards",    nom:"Cake boards",               categorie:"support",     qteDispo:20, coutUnitaire:0.8,  seuilAlerte:5,  statut:"disponible", utilisation:"Base sous les gâteaux"},
  {id:"c_boites_bento",   nom:"Boîtes bento cake",         categorie:"emballage",   qteDispo:20, coutUnitaire:1.2,  seuilAlerte:5,  statut:"disponible"},
  {id:"c_boites_layer",   nom:"Boîtes layer cake",         categorie:"emballage",   qteDispo:10, coutUnitaire:2.5,  seuilAlerte:3,  statut:"disponible"},
  {id:"c_cartons_pat",    nom:"Cartons pâtisserie",        categorie:"emballage",   qteDispo:30, coutUnitaire:0.5,  seuilAlerte:10, statut:"disponible"},
  {id:"c_boites_repas",   nom:"Boîtes repas",              categorie:"emballage",   qteDispo:50, coutUnitaire:0.4,  seuilAlerte:15, statut:"disponible"},
  {id:"c_boites_cup",     nom:"Boîtes cupcakes",           categorie:"emballage",   qteDispo:30, coutUnitaire:0.8,  seuilAlerte:10, statut:"disponible"},
  {id:"c_pots_glace",     nom:"Pots à glace",              categorie:"emballage",   qteDispo:50, coutUnitaire:0.3,  seuilAlerte:10, statut:"disponible"},
  {id:"c_papier_cuis",    nom:"Papier cuisson",            categorie:"cuisson",     qteDispo:3,  coutUnitaire:2.0,  seuilAlerte:1,  statut:"disponible"},
  {id:"c_film_alim",      nom:"Film alimentaire",          categorie:"conservation",qteDispo:2,  coutUnitaire:3.5,  seuilAlerte:1,  statut:"disponible"},
  {id:"c_aluminium",      nom:"Papier aluminium",          categorie:"cuisson",     qteDispo:2,  coutUnitaire:2.8,  seuilAlerte:1,  statut:"disponible"},
  {id:"c_verrines",       nom:"Verrines",                  categorie:"service",     qteDispo:24, coutUnitaire:0.5,  seuilAlerte:6,  statut:"disponible"},
  {id:"c_gobelets",       nom:"Gobelets jetables",         categorie:"service",     qteDispo:100,coutUnitaire:0.1,  seuilAlerte:20, statut:"disponible"},
  {id:"c_serviettes",     nom:"Serviettes jetables",       categorie:"service",     qteDispo:200,coutUnitaire:0.05, seuilAlerte:50, statut:"disponible"},
  {id:"c_bougies_anniv",  nom:"Bougies anniversaire",      categorie:"decoration",  qteDispo:30, coutUnitaire:0.5,  seuilAlerte:5,  statut:"disponible"},
  {id:"c_rubans",         nom:"Rubans décoratifs",         categorie:"decoration",  qteDispo:10, coutUnitaire:1.5,  seuilAlerte:2,  statut:"disponible"},
  {id:"c_etiquettes",     nom:"Étiquettes personnalisées", categorie:"decoration",  qteDispo:100,coutUnitaire:0.1,  seuilAlerte:20, statut:"disponible"},
  {id:"c_stickers",       nom:"Stickers Bella'Food",       categorie:"decoration",  qteDispo:50, coutUnitaire:0.15, seuilAlerte:10, statut:"disponible"},
  {id:"c_sacs_kraft",     nom:"Sacs kraft",                categorie:"emballage",   qteDispo:40, coutUnitaire:0.3,  seuilAlerte:10, statut:"disponible"},
  {id:"c_poches_jet",     nom:"Poches jetables (50 pcs)",  categorie:"patisserie",  qteDispo:2,  coutUnitaire:6.0,  seuilAlerte:1,  statut:"disponible"},
  {id:"c_gants",          nom:"Gants jetables (boîte 50)", categorie:"hygiene",     qteDispo:2,  coutUnitaire:4.5,  seuilAlerte:1,  statut:"disponible"},
  {id:"c_charlottes",     nom:"Charlottes (boîte 50)",     categorie:"hygiene",     qteDispo:1,  coutUnitaire:3.0,  seuilAlerte:1,  statut:"faible"},
];

// ── Bibliothèque de recettes initiale (20 recettes) ────────
export const FOOD_RECETTES_INIT: Recette[] = [
  // ─ Pâtisserie ─
  {
    id:"r_layer_cake_base", nom:"Layer Cake 3 étages (base)", categorie:"cake", sousCat:"layer",
    difficulte:4, nbParts:12, statut:"validee",
    tempsPrepa:45, tempsCuisson:35, tempsRepos:120, tempsTotal:200, temperature:180,
    tags:["anniversaire","personnalisable","events"],
    ingredients:[
      {id:"s_farine",nom:"Farine T55",quantite:400,unite:"g",coutUnitaire:0.002},
      {id:"s_sucre_blanc",nom:"Sucre",quantite:300,unite:"g",coutUnitaire:0.003},
      {id:"s_oeufs",nom:"Œufs",quantite:6,unite:"piece",coutUnitaire:0.3},
      {id:"s_beurre",nom:"Beurre",quantite:200,unite:"g",coutUnitaire:0.012},
      {id:"s_lait",nom:"Lait",quantite:200,unite:"ml",coutUnitaire:0.001},
      {id:"s_levure_ch",nom:"Levure chimique",quantite:10,unite:"g",coutUnitaire:0.01},
      {id:"s_vanille",nom:"Extrait de vanille",quantite:5,unite:"ml",coutUnitaire:0.05},
    ],
    etapes:[
      "Préchauffer le four à 180°C. Beurrer et fariner 3 moules identiques.",
      "Dans un cul de poule, fouetter le beurre mou et le sucre jusqu'à obtenir un mélange pâle et crémeux.",
      "Ajouter les œufs un par un, en fouettant bien entre chaque.",
      "Incorporer la farine tamisée et la levure en alternance avec le lait.",
      "Ajouter la vanille et mélanger délicatement.",
      "Répartir la pâte équitablement dans les 3 moules. Cuire 30-35 min.",
      "Vérifier la cuisson avec un couteau — il doit sortir propre.",
      "Laisser refroidir 15 min dans les moules, puis démouler sur grille.",
      "Laisser refroidir complètement (2h min) avant de garnir.",
      "Monter les couches avec la ganache ou crème choisie.",
      "Couvrir l'extérieur de crème, lisser et décorer selon le thème.",
    ],
    astuces:["Niveler les biscuits pour un résultat parfait","Choisir les saveurs en fonction du thème"],
    variantes:["Chocolat","Citron","Vanille fraise","Red velvet"],
    coutMatiere:8, coutConsommables:5, prixRevient:13, prixConseille:45, prixPremium:65,
    margeEstimee:32, tempsProduction:200,
    conservation:"3 jours au réfrigérateur",
    paysOrigine:"International", allergenes:["gluten","lait","oeufs"],
  },
  {
    id:"r_bento_cake", nom:"Bento Cake individuel", categorie:"cake", sousCat:"bento",
    difficulte:3, nbParts:1, statut:"validee",
    tempsPrepa:20, tempsCuisson:20, tempsRepos:30, tempsTotal:70, temperature:175,
    tags:["anniversaire","cadeau","individual"],
    ingredients:[
      {id:"s_farine",nom:"Farine T55",quantite:80,unite:"g"},
      {id:"s_sucre_blanc",nom:"Sucre",quantite:60,unite:"g"},
      {id:"s_oeufs",nom:"Œufs",quantite:1,unite:"piece",coutUnitaire:0.3},
      {id:"s_beurre",nom:"Beurre",quantite:40,unite:"g",coutUnitaire:0.012},
      {id:"s_lait",nom:"Lait",quantite:50,unite:"ml"},
    ],
    etapes:[
      "Mélanger les ingrédients secs.",
      "Incorporer beurre fondu, œuf, lait.",
      "Cuire dans moule individuel 18-20 min à 175°C.",
      "Refroidir, garnir et décorer selon commande.",
    ],
    coutMatiere:2, coutConsommables:4, prixRevient:6, prixConseille:25, prixPremium:35,
    margeEstimee:19, tempsProduction:70,
    conservation:"2 jours au réfrigérateur",
    allergenes:["gluten","lait","oeufs"],
  },
  {
    id:"r_colombo_poulet", nom:"Colombo de poulet", categorie:"repas_guyanais", sousCat:"plat_antillais",
    difficulte:3, nbParts:4, statut:"validee",
    tempsPrepa:20, tempsCuisson:45, tempsTotal:65,
    tags:["guyanais","antillais","creole","events"],
    ingredients:[
      {id:"s_poulet",nom:"Poulet",quantite:1,unite:"kg",coutUnitaire:8},
      {id:"s_colombo_pdr",nom:"Poudre à colombo",quantite:30,unite:"g",coutUnitaire:0.08},
      {id:"s_lait_coco",nom:"Lait de coco",quantite:400,unite:"ml",coutUnitaire:0.003},
      {id:"ing_ail",nom:"Ail",quantite:4,unite:"piece",coutUnitaire:0.2},
      {id:"ing_oignon",nom:"Oignon",quantite:2,unite:"piece",coutUnitaire:0.3},
      {id:"ing_tomate",nom:"Tomates",quantite:2,unite:"piece",coutUnitaire:0.4},
      {id:"ing_citron",nom:"Citron vert",quantite:1,unite:"piece",coutUnitaire:0.3},
    ],
    epices:["Colombo","Cumin","Curcuma","Piment antillais","Cive"],
    proteines:["Poulet"],
    etapes:[
      "Mariner le poulet avec le colombo, l'ail écrasé, le jus de citron et les épices (1h minimum).",
      "Faire revenir l'oignon émincé dans l'huile jusqu'à translucide.",
      "Ajouter le poulet mariné et faire dorer sur toutes les faces.",
      "Incorporer les tomates concassées et laisser compoter 5 min.",
      "Verser le lait de coco et les épices restantes.",
      "Laisser mijoter 35-40 min à feu doux en remuant régulièrement.",
      "Ajuster l'assaisonnement. Servir avec le riz djon djon ou blanc.",
    ],
    astuces:["La marinade longue est la clé du goût","Cuire à feu très doux pour garder le poulet tendre"],
    coutMatiere:12, prixConseille:null, tempsProduction:65,
    conservation:"2 jours au réfrigérateur",
    paysOrigine:"Guyane / Antilles", allergenes:[],
  },
  {
    id:"r_dombres_crevettes", nom:"Dombrés aux crevettes", categorie:"repas_guyanais", sousCat:"plat_traditionnel",
    difficulte:4, nbParts:4, statut:"validee",
    tempsPrepa:30, tempsCuisson:40, tempsTotal:70,
    tags:["traditionnel","guyanais","creole","events"],
    ingredients:[
      {id:"ing_crevettes",nom:"Crevettes fraîches",quantite:500,unite:"g",coutUnitaire:0.025},
      {id:"s_farine",nom:"Farine T55",quantite:200,unite:"g",coutUnitaire:0.002},
      {id:"ing_ail",nom:"Ail",quantite:3,unite:"piece",coutUnitaire:0.2},
      {id:"ing_oignon",nom:"Oignon",quantite:1,unite:"piece",coutUnitaire:0.3},
      {id:"s_lait_coco",nom:"Lait de coco",quantite:200,unite:"ml"},
      {id:"ing_piment",nom:"Piment",quantite:1,unite:"piece",coutUnitaire:0.2},
    ],
    epices:["Bois d'inde","Cive","Thym","Piment doux"],
    proteines:["Crevettes"],
    etapes:[
      "Préparer les dombrés : mélanger farine, sel, un peu d'eau pour obtenir une pâte ferme. Faire des petites boules.",
      "Cuire les dombrés dans de l'eau bouillante salée 15 min. Égoutter.",
      "Faire sauter les crevettes assaisonnées à l'ail dans l'huile.",
      "Ajouter oignon, piment, épices et laisser mijoter 5 min.",
      "Incorporer le lait de coco et les dombrés.",
      "Laisser mijoter 10 min à feu doux pour mélanger les saveurs.",
    ],
    coutMatiere:14, prixConseille:null, tempsProduction:70,
    conservation:"1 jour au réfrigérateur",
    paysOrigine:"Guyane", allergenes:["gluten","crustaces"],
  },
  {
    id:"r_jus_canne", nom:"Jus de canne frais", categorie:"jus", sousCat:"frais",
    difficulte:1, nbParts:1, statut:"validee",
    tempsPrepa:5, tempsCuisson:0, tempsTotal:5,
    tags:["frais","local","naturel"],
    ingredients:[{id:"ing_canne",nom:"Canne à sucre",quantite:200,unite:"g"}],
    etapes:["Éplucher et couper la canne.", "Passer à l'extracteur ou presser.", "Filtrer et servir immédiatement sur glaçons."],
    astuces:["Ajouter du citron vert pour un goût plus frais","Servir immédiatement — s'oxyde vite"],
    coutMatiere:0.5, coutConsommables:0.5, prixConseille:3, margeEstimee:2,
    conservation:"Immédiatement", allergenes:[],
  },
  {
    id:"r_glace_coco", nom:"Glace coco artisanale", categorie:"glace", sousCat:"artisanale",
    difficulte:3, nbParts:6, statut:"validee",
    tempsPrepa:15, tempsCuisson:0, tempsRepos:240, tempsTotal:255,
    tags:["tropical","fait_maison","artisanal"],
    ingredients:[
      {id:"s_lait_coco",nom:"Lait de coco",quantite:400,unite:"ml"},
      {id:"s_creme_liq",nom:"Crème liquide",quantite:200,unite:"ml"},
      {id:"s_sucre_blanc",nom:"Sucre",quantite:80,unite:"g"},
      {id:"ing_noix_coco",nom:"Noix de coco râpée",quantite:50,unite:"g"},
    ],
    etapes:[
      "Chauffer légèrement le lait de coco et le sucre pour dissoudre.",
      "Laisser refroidir, incorporer la crème et la noix de coco râpée.",
      "Turbiner en sorbetière 25 min, ou verser en bac et remuer toutes les heures pendant 4h.",
      "Mettre au congélateur jusqu'à utilisation.",
    ],
    coutMatiere:3, coutConsommables:1, prixConseille:3, margeEstimee:1.5,
    conservation:"2 semaines au congélateur", allergenes:["lait"],
  },
  {
    id:"r_cupcakes_deco", nom:"Cupcakes décorés", categorie:"cupcake", sousCat:"deco",
    difficulte:3, nbParts:12, statut:"validee",
    tempsPrepa:30, tempsCuisson:20, tempsRepos:30, tempsTotal:80, temperature:170,
    tags:["anniversaire","events","personnalisable"],
    ingredients:[
      {id:"s_farine",nom:"Farine T55",quantite:180,unite:"g"},
      {id:"s_sucre_blanc",nom:"Sucre",quantite:150,unite:"g"},
      {id:"s_oeufs",nom:"Œufs",quantite:2,unite:"piece",coutUnitaire:0.3},
      {id:"s_beurre",nom:"Beurre",quantite:100,unite:"g"},
      {id:"s_lait",nom:"Lait",quantite:120,unite:"ml"},
      {id:"s_levure_ch",nom:"Levure",quantite:7,unite:"g"},
    ],
    etapes:[
      "Fouetter le beurre mou et le sucre.",
      "Ajouter les œufs un à un.",
      "Alterner farine+levure et lait.",
      "Remplir les caissettes aux 2/3.",
      "Cuire 18-20 min à 170°C.",
      "Refroidir et décorer à la poche selon le thème.",
    ],
    coutMatiere:2.5, coutConsommables:3, prixConseille:28, margeEstimee:22.5,
    conservation:"2 jours à température ambiante",
    allergenes:["gluten","lait","oeufs"],
  },
  {
    id:"r_the_glace_citronelle", nom:"Thé glacé citronnelle", categorie:"the_glace", sousCat:"herbes",
    difficulte:1, nbParts:4, statut:"validee",
    tempsPrepa:5, tempsCuisson:0, tempsRepos:60, tempsTotal:65,
    tags:["frais","local","naturel"],
    ingredients:[
      {id:"ing_citronelle",nom:"Citronnelle fraîche",quantite:4,unite:"piece"},
      {id:"s_sucre_blanc",nom:"Sucre",quantite:60,unite:"g"},
      {id:"ing_citron_v",nom:"Citron vert",quantite:1,unite:"piece"},
      {id:"ing_eau",nom:"Eau bouillante",quantite:1,unite:"L"},
    ],
    etapes:[
      "Écraser les tiges de citronnelle pour libérer les arômes.",
      "Infuser dans l'eau bouillante 10 min.",
      "Ajouter le sucre et mélanger.",
      "Filtrer et laisser refroidir.",
      "Servir sur glaçons avec le jus de citron vert.",
    ],
    coutMatiere:1, coutConsommables:0.5, prixConseille:3, margeEstimee:1.5,
    conservation:"24h au réfrigérateur", allergenes:[],
  },
  {
    id:"r_riz_djon_djon", nom:"Riz djon djon", categorie:"riz", sousCat:"parfume",
    difficulte:3, nbParts:6, statut:"validee",
    tempsPrepa:15, tempsCuisson:25, tempsRepos:15, tempsTotal:55,
    tags:["haitien","traditionnel","unique","events"],
    ingredients:[
      {id:"ing_djon_djon",nom:"Champignons djon djon (séchés)",quantite:50,unite:"g"},
      {id:"ing_riz",nom:"Riz",quantite:400,unite:"g"},
      {id:"ing_ail",nom:"Ail",quantite:3,unite:"piece"},
      {id:"ing_oignon",nom:"Oignon",quantite:1,unite:"piece"},
      {id:"ing_cive",nom:"Cive",quantite:2,unite:"piece"},
      {id:"ing_thym",nom:"Thym",quantite:2,unite:"piece"},
    ],
    etapes:[
      "Réhydrater les djon djon dans 600ml d'eau chaude 15 min. Filtrer en conservant l'eau noire.",
      "Faire revenir l'ail et l'oignon dans l'huile.",
      "Ajouter le riz lavé et nacrer 2 min.",
      "Verser l'eau de djon djon (quantité pour le riz) + épices.",
      "Cuire à feu doux 20 min à couvert.",
      "Laisser reposer 10 min avant de servir.",
    ],
    astuces:["L'eau des djon djon donne la couleur et le goût uniques"],
    coutMatiere:6, prixConseille:null, tempsProduction:55,
    paysOrigine:"Haïti", allergenes:[],
  },
  {
    id:"r_sauce_burger", nom:"Sauce burger maison", categorie:"sauce", sousCat:"froide",
    difficulte:1, nbParts:8, statut:"validee",
    tempsPrepa:10, tempsCuisson:0, tempsTotal:10,
    tags:["rapide","polyvalent"],
    ingredients:[
      {id:"ing_mayo",nom:"Mayonnaise",quantite:100,unite:"g"},
      {id:"ing_ketchup",nom:"Ketchup",quantite:30,unite:"g"},
      {id:"ing_cornichons",nom:"Cornichons émincés",quantite:20,unite:"g"},
      {id:"ing_moutarde",nom:"Moutarde de Dijon",quantite:10,unite:"g"},
      {id:"ing_ail",nom:"Ail en poudre",quantite:2,unite:"g"},
      {id:"ing_paprika",nom:"Paprika fumé",quantite:2,unite:"g"},
    ],
    etapes:[
      "Mélanger tous les ingrédients.",
      "Ajuster l'assaisonnement selon le goût.",
      "Réserver au frais 30 min avant utilisation.",
    ],
    coutMatiere:1.5, prixConseille:null,
    conservation:"5 jours au réfrigérateur", allergenes:["oeufs","moutarde"],
  },
  {
    id:"r_entremets_framboise", nom:"Entremets framboise & chocolat blanc", categorie:"entremet",
    sousCat:"mousse", difficulte:5, nbParts:8, statut:"validee",
    tempsPrepa:60, tempsCuisson:15, tempsRepos:360, tempsTotal:435, temperature:165,
    tags:["premium","framboise","chocolat_blanc"],
    ingredients:[
      {id:"s_choc_blanc",nom:"Chocolat blanc",quantite:200,unite:"g"},
      {id:"s_creme_liq",nom:"Crème liquide 35%",quantite:400,unite:"ml"},
      {id:"ing_framboises",nom:"Framboises",quantite:300,unite:"g"},
      {id:"s_sucre_blanc",nom:"Sucre",quantite:80,unite:"g"},
      {id:"ing_gelatine",nom:"Gélatine en feuilles",quantite:6,unite:"piece"},
    ],
    etapes:[
      "Faire un biscuit Joconde ou dacquoise. Cuire et refroidir.",
      "Préparer le coulis framboise : mixer + sucre + passer au tamis.",
      "Faire fondre le chocolat blanc au bain marie.",
      "Ramollir la gélatine dans l'eau froide. L'incorporer au coulis chaud.",
      "Monter la crème en chantilly ferme.",
      "Incorporer délicatement le mélange chocolat-framboise à la chantilly.",
      "Monter l'entremets dans un cercle : biscuit + coulis + mousse.",
      "Congeler 6h minimum. Décorer au nappage miroir ou velours.",
    ],
    coutMatiere:12, coutConsommables:4, prixRevient:16, prixConseille:null, prixPremium:null,
    margeEstimee:null,
    conservation:"3 jours au réfrigérateur / 1 mois congelé avant nappage",
    allergenes:["gluten","lait","oeufs"],
  },
  {
    id:"r_cookies_choc", nom:"Cookies chocolat fondants", categorie:"patisserie", sousCat:"biscuits",
    difficulte:2, nbParts:20, statut:"validee",
    tempsPrepa:15, tempsCuisson:12, tempsRepos:30, tempsTotal:57, temperature:180,
    tags:["chocolat","fondant","rapide"],
    ingredients:[
      {id:"s_farine",nom:"Farine T55",quantite:280,unite:"g"},
      {id:"s_sucre_cas",nom:"Cassonade",quantite:180,unite:"g"},
      {id:"s_beurre",nom:"Beurre pommade",quantite:150,unite:"g"},
      {id:"s_oeufs",nom:"Œufs",quantite:2,unite:"piece"},
      {id:"s_choc_noir",nom:"Pépites chocolat noir",quantite:200,unite:"g"},
      {id:"ing_fleur_sel",nom:"Fleur de sel",quantite:3,unite:"g"},
      {id:"s_levure_ch",nom:"Bicarbonate de soude",quantite:5,unite:"g"},
    ],
    etapes:[
      "Fouetter le beurre et la cassonade jusqu'à blanchiment.",
      "Incorporer les œufs un par un.",
      "Ajouter la farine et le bicarbonate tamisés.",
      "Incorporer les pépites de chocolat.",
      "Former des boules et réfrigérer 30 min.",
      "Cuire sur plaque 11-13 min à 180°C — sortir encore fondants.",
      "Saupoudrer de fleur de sel à la sortie du four.",
    ],
    coutMatiere:4, coutConsommables:1, prixConseille:12, margeEstimee:7,
    conservation:"5 jours boîte hermétique",
    allergenes:["gluten","lait","oeufs"],
  },
  // Smoothie et boissons
  {
    id:"r_smoothie_tropicale", nom:"Smoothie tropical maison", categorie:"smoothie",
    difficulte:1, nbParts:2, statut:"validee",
    tempsPrepa:8, tempsCuisson:0, tempsTotal:8,
    tags:["frais","tropical","vitamine"],
    ingredients:[
      {id:"ing_mangue",nom:"Mangue",quantite:200,unite:"g"},
      {id:"ing_ananas",nom:"Ananas",quantite:150,unite:"g"},
      {id:"ing_banane",nom:"Banane",quantite:1,unite:"piece"},
      {id:"ing_coco_eau",nom:"Eau de coco",quantite:200,unite:"ml"},
    ],
    etapes:["Peler et couper les fruits.", "Mixer avec l'eau de coco.", "Servir immédiatement sur glaçons."],
    coutMatiere:2, coutConsommables:0.5, prixConseille:null, margeEstimee:null,
    conservation:"Immédiatement", allergenes:[],
  },
  // Recettes Brunch
  {
    id:"r_pancakes", nom:"Pancakes moelleux", categorie:"brunch",
    difficulte:2, nbParts:8, statut:"validee",
    tempsPrepa:10, tempsCuisson:20, tempsTotal:30,
    tags:["brunch","rapide","enfants"],
    ingredients:[
      {id:"s_farine",nom:"Farine T55",quantite:200,unite:"g"},
      {id:"s_sucre_blanc",nom:"Sucre",quantite:30,unite:"g"},
      {id:"s_oeufs",nom:"Œufs",quantite:2,unite:"piece"},
      {id:"s_lait",nom:"Lait",quantite:250,unite:"ml"},
      {id:"s_beurre",nom:"Beurre fondu",quantite:30,unite:"g"},
      {id:"s_levure_ch",nom:"Levure chimique",quantite:10,unite:"g"},
    ],
    etapes:[
      "Mélanger les ingrédients secs, puis les liquides séparément.",
      "Combiner sans trop travailler la pâte.",
      "Cuire des petits disques dans une poêle légèrement beurrée.",
      "Retourner quand des bulles se forment. Cuire 1 min de l'autre côté.",
    ],
    coutMatiere:1.5, prixConseille:null,
    conservation:"À consommer chaud", allergenes:["gluten","lait","oeufs"],
  },
];
